name = "NSHeat"
uuid = "a4d194c8-304d-11e9-1e2b-63c3517fb552"
authors = ["basspale <k.yanagi07@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
ODEInterfaceDiffEq = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
